SELECT
licenca AS Numero_Alvara_Licenca,
num_proc AS Numero_Processo,
cod_dlf AS id_orgao_SISLIC,
CAST(Dt_emissao AS DATETIME) AS Data_emissao,
CAST(Dt_Inicio_Validade AS DATETIME) AS Data_Inicio_Validade,
CAST(dt_Venc AS DATETIME) AS Data_Vencimento,
CAST(CAST(Prazo AS FLOAT64) AS int64) AS Prazo,
Num_darm_pg AS Numero_DARM_Pago,
CAST(l_Lic as float64) AS Valor_DARM,
Requerente AS Requerente,
CNPJ_CPF AS CNPJ_CPF,
clogra AS Id_Logra,
tipo AS Tipo_Logradouro,
nobreza AS Nobreza_Logradouro,
preposicao AS Preposicao_Logradouro,
nomelogra AS Nome_Logradouro,
num AS Numero_Porta,
complemento AS Complemento_Numero_Porta,
paa AS PAA,
pal AS PAL,
PLT AS PLT,
quadra AS Quadra,
lote AS Lote,
cb AS Centro_Bairro,
zona AS Zona,
subzona AS Subzona,
cep AS CEP,
bsmp AS Cod_Bairro,
num_suple AS Numero_Logradouro_Suplementar,
InscricaoIMOVEL AS Inscricao_Imovel,
ID_TpInscricaoIMOVEL AS ID_Tipo_Inscricao_Imovel,
Uso_atividade AS Uso_Atividade,
Implantacao AS Implantacao,
CAST(CAST(tot_edif  AS FLOAT64) as int64) AS Total_Edificacoes,
CAST(area_constr AS FLOAT64) AS Area_Construida,
CAST(area_acrescida AS FLOAT64) AS Area_Acrescida,
CAST(area_reduzida AS FLOAT64) AS Area_Reduzida,
CAST(area_util AS FLOAT64) AS Area_Util,
CAST(AREA_TOTAL_EDIFICADA AS FLOAT64) AS Area_Total_Edificada,
CAST(AREA_EXISTENTE_DECLARADA_RESPONSAVEL AS BOOL) AS Area_Existente_Declarada_Responsavel,
CAST(AreaTotal_Loteamento AS FLOAT64) AS Area_Total_Loteamento,
CAST(MetrosLineares_ObrasUrbanizacao AS FLOAT64) AS Metros_Lineares_Obras_Urbanizacao,
CAST(CAST(VagasExternasDescobertas  AS FLOAT64) AS INT64) AS Vagas_Externas_Descobertas,
CAST(CAST(VagasExternasCobertas  AS FLOAT64) AS INT64) AS Vagas_Externas_Cobertas,
CAST(CAST(VagasPavimentos  AS FLOAT64) AS INT64) AS Vagas_Pavimentos,
nome_preo AS Nome_PREO,
crea_preo AS CREA_PREO,
RRT_ART_PREO AS RRT_ART_PREO,
Nome_PRPA AS Nome_PRPA,
Crea_PRPA AS CREA_PRPA,
RRT_ART_PRPA AS RRT_ART_PRPA,
CAST(Grupamento AS BOOL) AS Grupamento,
CAST(Tot_etapas AS FLOAT64) AS Total_Etapas,
CAST(Tot_edif_etapa AS FLOAT64) AS Total_Edificacoes_Etapa,
CAST(area_tot_etapa AS FLOAT64) AS Area_Total_Etapa,
Lic_concedida AS Licenca_Concedida,
Edif_Pav AS Descricao_Edificacao_Concatenada,
CAST(ConcedeNumeracao  as bool) AS Concede_Numeracao,
NumConcedida AS Numeracao_Concedida,
OBS AS Observacao,
CAST(cancelado AS BOOL) AS Cancelado,
CAST(OrgaoCentral AS BOOL) AS Licenca_Orgao_Central,
CODORGAO_ESPECIAL AS Cod_Orgao_Especial,
CAST(Licenca_Loteamento AS BOOL) AS Licenca_Loteamento,
CAST(LicencaAvulsa AS BOOL) AS Licenca_Avulsa,
CAST(LoteamentoNovoModelo AS BOOL) AS Loteamento_Novo_Modelo,
CAST(AprovacaoParcelamento AS BOOL) AS Aprovacao_Parcelamento,
CAST(CAST(Totalunidades AS FLOAT64) AS INT64) AS Total_Unidades,
CAST(CAST(LicOnLine_ID_Requerimento AS FLOAT64) AS INT64) AS ID_Requerimento_Licenca_OnLine
FROM `rj-smdue.adm_licenca_urbanismo_staging.alvara_obra_privada`